# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Tnk factory
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
logo: "/assets/images/logo-bk.png"
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll





aux_links:
  "tnk factory":
    - "//tnkfactory.com"
aux_links_new_tab: true

heading_anchors: true


# Define Jekyll collections
collections:
  join:
    permalink: "/:collection/:path/"
    output: true
  # Define a collection named "docs", its documents reside in the "_docs" directory
  publisher:
    permalink: "/:collection/:path/"
    output: true
  sdk_da:
    permalink: "/:collection/:path/"
    output: true
  incentive:
    permalink: "/:collection/:path/"
    output: true
  sdk_rwd:
    permalink: "/:collection/:path/"
    output: true
  utilities:
    permalink: "/:collection/:path/"
    output: true


just_the_docs:
  # Define which collections are used in just-the-docs
  collections:
    join:
      # Give the collection a name
      name: Join
      # Exclude the collection from the navigation
      # Supports true or false (default)
      nav_exclude: false
      # Exclude the collection from the search
      # Supports true or false (default)
      search_exclude: false
    # Reference the "docs" collection
    # Reference the "docs" collection
    publisher:
      # Give the collection a name
      name: publisher
      # Exclude the collection from the navigation
      # Supports true or false (default)
      nav_exclude: false
      # Exclude the collection from the search
      # Supports true or false (default)
      search_exclude: false
    # Reference the "docs" collection
    sdk_da:
      # Give the collection a name
      name: sdk_da
      # Exclude the collection from the navigation
      # Supports true or false (default)
      nav_exclude: false
      # Exclude the collection from the search
      # Supports true or false (default)
      search_exclude: false
    incentive:
      # Give the collection a name
      name: incentive
      # Exclude the collection from the navigation
      # Supports true or false (default)
      nav_exclude: false
      # Exclude the collection from the search
      # Supports true or false (default)
      search_exclude: false
    # Reference the "docs" collection
    sdk_rwd:
      # Give the collection a name
      name: sdk_rwd
      # Exclude the collection from the navigation
      # Supports true or false (default)
      nav_exclude: false
      # Exclude the collection from the search
      # Supports true or false (default)
      search_exclude: false
    # Reference the "docs" collection
    utilities:
      # Give the collection a name
      name: Utilities
      # Exclude the collection from the navigation
      # Supports true or false (default)
      nav_exclude: false
      # Exclude the collection from the search
      # Supports true or false (default)
      search_exclude: false


# Build settings
remote_theme: pmarsceill/just-the-docs
#theme: just-the-docs
# theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-target-blank
# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
